host: 88.212.206.137
ports:
  - '11111'
  - '11211'
  - '11311'
logNet: false
repl: true
defaults:
  reconnect: false
  reconnectForDailyBonus: false
  checkModerators: true
  autoPlay: true
  playInClan: true
  locationId: 4
  surrender: false
  roomId: null
  joinId: null
  clanIdToJoin: 0
  buyVIP: false
  donateLevel: null
players:
  - session: >-
      useApiType=vk&viewer_id=149194937&access_token=vk1.a.Dajlz-udNF_zuBnOOHnf8ToAFSUwn_FYjCZvrt2ujHD14XYWTPx80J1LO6Nd-b4akD56_aEfIMPtmEM3jJS363BaJnyXElSU4W_IQMue1RplHbdZCgRcnuhJIeuS6ve-o3IzQYQip64KGuLURRv68InXMty79KQABmnY0_uirCipm8QGfsIygVVAn_nfdzdv&api_url=https://api.vk.com/method/&auth_key=&token=c1d70866e776e5a2d5f33db4d49ffb9f&userId=149194937&net_type=0&OAuth=1&protocol=https:
  # - session: >-
  #     СЕССИЯ ВТОРОГО ИГРОКА